### ISSUE TITLE
Optimize calculate_perplexity function

### ISSUE THREAD

**Issue by 87875172** [compbiomed/celda#112]
calculate_perplexity function generates Inf for very large completeLogLik. Can skip taking exp first then log by doing log(1) - mean(completeLogLik)

**Comment by definitelysean** [comment]
Hey Zhe, I'm actually pretty bad at math, can you explain how the proposed
formula you provided relates to the existing calculation?

Note that the perplexity is defined as "the reciprocal geometric mean of
the token likelihoods in the test corpus given the model" where the token
lilkelihoods are the completeLogLik values in celda. The current version
"un-logs" the completeLogLik and takes the inverse. I think technically
this isn't even the correct formula, though, given that the function
currently takes the *arithmetic* mean and not the geometric mean.

**Comment by 87875172** [comment]
Well I don't know how perplexity is defined and how it should be calculated. By looking at the calculate_perplexity function in model_performance.R I just thought it was calculated like this
![per1](https://user-images.githubusercontent.com/16454489/27647898-d585029a-5bfa-11e7-90e4-143174ff990e.png)
which is equivalent to 
![per2](https://user-images.githubusercontent.com/16454489/27647928-f5e1e2f6-5bfa-11e7-8233-38f75bbbd9b6.png)

For geometric mean just change avg to geometric mean. This way there's no need to exponentiate and maybe no need to use Rmpfr::mpfr and should generate non Inf values.

**Comment by definitelysean** [comment]
The formula for perplexity does not have the log up front as you wrote;
it's just the fraction portion of your first formula, so these are not
equivalent. Your formula would be for the log perplexity.

The log perplexity is used for visualization purposes only, because the raw
perplexity scores are very very huge and *need* to be represnted with Rmpfr
numbers, because they are so large that R cannot represent them.
*Because ggplot2
does not work with Rmpfr numbers*, we need some internal R floating point
number to make the plots, which is why I take the log in order to be able
to represent them.

Does that make sense?
