### ISSUE TITLE
Consistent function naming scheme

### ISSUE THREAD

**Issue by joshua-d-campbell** [compbiomed/celda#137]
Some functions use "_" to separate words. Others use capitalization to separate words. We should just pick a convention and stick with it. I prefer capitalization, but don't really care that much. Some function names are also a bit long

**Comment by definitelysean** [comment]
@joshua-d-campbell we can use a linter in order to enforce a consistent style which will cause a build break when people don't conform to a style.

Let's change our function style to match the [Bioconductor standards](https://www.bioconductor.org/developers/how-to/coding-style/), which is camel case (e.g. someFunctionName() ). I'll get this done today (9/19)

**Comment by definitelysean** [comment]
@joshua-d-campbell This will also mean renaming our model functions (celda_C => celdaC). Does that read as well to you?

**Comment by joshua-d-campbell** [comment]
I like the idea of using camel case. Changing the names of all the functions may take a while. We should probably create a release (e.g. v1.1) with current naming scheme that is stable and then change naming scheme in next iteration.
