### ISSUE TITLE
celda "sample.label" parameter

### ISSUE THREAD

**Issue by joshua-d-campbell** [compbiomed/celda#148]
Right now it requires a numerical vector. But underlying models will take factors or character strings. Celda wrapper should do the same.

**Comment by definitelysean** [comment]
Hey @joshua-d-campbell , each of the model functions right now work with factor or charcaters by converting them to numeric, so that functionality is in place. I realized the celda documentation didn't reflect that, and additionally that the parameter checking for the wrapper only accepted numeric vectors, so I fixed both.

Let me know if there's still something to be done on this one.
