### ISSUE TITLE
Improved Perplexity

### ISSUE THREAD

**Issue by definitelysean** [compbiomed/celda#187]
Implement model-derived perplexity functions for each of celda_C, G, CG models. Should be done in conjunction with #154 .

**Comment by definitelysean** [comment]
@joshua-d-campbell I'm assuming the best way to visualize this is to let the user specify the # of resamples, and then to visualize the perplexity as it currently works for celda_C and celda_G.

So, the user would say "evaluate the perplexity 10 times for each K", and we'd show a plot w/ perplexity on Y, and the 10 perplexities calculated for each K in the result list.

Does that sound good?

**Comment by definitelysean** [comment]
Also, can we consider removing the "loglik" visualization type? Leaving it in is fine, but it makes the code a little more complicated to handle this other measure. 

E.g. currently, if you call visualizeModelPerformance(celdaC_mod, ..., method="perplexity"), the S3 generic routes to the model's implementation, which routes back out to calculatePerformanceMetric (a generic function for calculating performance metrics), which routes you _back_ to the model itself.

**Comment by joshua-d-campbell** [comment]
Yes, I think you are describing things correctly. celda_C and celda_G should have perplexity on y-axis and K or L on x-axis. Multiple perplexities per K/L can be visualized with a boxplot to show the distribution. If that is too complicated, then just showing the mean or median will be fine. 

For celda_CG, it should be perplexity on y-axis and K on x-axis. There should then be different colored lines or points for different L's as a function of K.

Yes, remove current version of loglik.

**Comment by definitelysean** [comment]
@joshua-d-campbell can you check out celda_C's calculatePerplexity on the dev branch (see commit above)? 

It's a little slow right now by my testing, but I haven't been passing sparse matrices for the counts parameter, which might make the matrix multiplications faster.

I tried a couple of ways to concatenate the original and resampled counts matrices into one giant matrix, and then multiply phi/theta/sl accordingly to make it a one-step calculation, but it was really ugly. Let me know if you can think of a better way to do it.

In the meantime I'll implement this for celda_G and CG, and incorporate their output into visualizeModelPerformance()

**Comment by joshua-d-campbell** [comment]
@definitelysean Overall it looks like it is working. Here are a few changes:

1) Have a function just for calculating the perplexity of a given counts matrix and model (with no resampling or x-validation). This function needs parameter for the original data as well as test data (set to NULL by default). If null, then the perplexity on the original counts matrix will be caculated, otherwise it is done on the test data. You will need a parameter for test sample labels as well.
2) Have another function which takes in a celda list object and counts matrix. This can do the resampling and then calculate the perplexity for each model in the celda list against the resampled data using the function from #1. This function should plot the results or return an object that can plotted with another function.
3) Also the count checksum is not be properly stored in the celda model object so this function was throwing an error. I will open up another issue

**Comment by definitelysean** [comment]
(For posterity: #190 covers issue 3 above)

**Comment by definitelysean** [comment]
This was merged into master in PR #198

**Comment by definitelysean** [comment]
Realized I needed to do some additional work to make this function work for non-celda_CG results.

**Comment by definitelysean** [comment]
https://github.com/compbiomed/celda/commit/61cb434c298ca5cf60c0958c950f505b84b58fc3
