### ISSUE TITLE
Set max.iter When Running Celda In Tests

### ISSUE THREAD

**Issue by definitelysean** [compbiomed/celda#192]
Currently, the basic tests in the testthat tests start by generating simulated data and then running celda. This adds a lot of time into running the test suite, which should ideally run very quickly. 

@ykoga07 , can you run those chunks of code and save them directly into the tests directory, and then rather than run celda before the tests, load() the celda results ahead of time? This should do the trick.

**Comment by joshua-d-campbell** [comment]
@definitelysean It is a bit tricky though because we need to test that each models run correctly without any run time errors. The simulated dataset should be small and only a small number of iterations should be run (i.e. stop.iter = 10). As long as it runs in a few minutes, I'm okay with it. 

Also, if running Rtsne, we may want to lower the number of iterations as well (i.e. 100) as the goal isn't to get the perfect result, but just to run everything.

**Comment by definitelysean** [comment]
@joshua-d-campbell that makes sense. I think stop-iterations should improve the runtime.

I think the runtime of the test suite can be an impediment to running it, especially for contributors outside our group (and my lazy butt...), so ideally it should run as quickly as possible.
