### ISSUE TITLE
Remove "..." from function arguments

### ISSUE THREAD

**Issue by joshua-d-campbell** [compbiomed/celda#211]
these are in several functions like celda_CG. However if someone enters an incorrect argument (i.e. misspells it), then it won't through an error and the default parameter of the argument will be used.

**Comment by definitelysean** [comment]
@joshua-d-campbell in a lot of cases this is necessary so that full specification of all of the arguments isn't necessary when defining the generic function. For example, the documentation for a generic function that has celda_C/G/CG implementations would have to include K and L as defined arguments, which means that we laboriously need to specify something like "@param K the number of cell clusters; only applies to celda_C and celda_CG models" and hope that the user reads the whole line. 

I'll double back specifically on the celda_* model functions and look at changing those to only accept the specified arguments.

**Comment by joshua-d-campbell** [comment]
Right - mainly just for celda_* models as I don't think they need the "..."
