### ISSUE TITLE
Install Documentation

### ISSUE THREAD

**Issue by bretonics** [compbiomed/celda#276]
Write more specific installation instructions. Current [installation instructions](https://github.com/compbiomed/celda#installation-instructions) should include:

- [ ] R version support
- [ ] Maybe include package dependencies?

Currently **R version 3.5.0 is not** supported. **libgit2** required for devtools package install. Not sure if this is dependent on a `brew` install and not affecting install from CRAN source. devtools dependency is solved via `brew install libgit2`, but Celda won't support R 3.5.0 yet as lintr, MAST, SummarizedExperiment, and GenomicRanges packages do not support R version 3.5.0.

Can confirm install works as expected using R 3.4.4.

**Comment by bretonics** [comment]
That is interesting as R 3.5.* reports lintr, MAST, SummarizedExperiment, and GenomicRanges packages are not supported for that particular R version.

libgit2 definitely addresses the devtools package install issue.

**Comment by definitelysean** [comment]
@bretonics Doubling back; did you try to do a fresh biocLite() and update relevant packages in your R 3.5? Things can get a little mixed-and-matched when there's multiple versions of R on the same machine.

**Comment by definitelysean** [comment]
@bretonics, I had Carter run a fresh install of celda on R 3.5 and he got all the package dependencies resolved successfully. I think you might have packages that were compiled in previous versions of R. Also suspicious is that SummarizedExperiment, MAST etc. are Bioconductor packages, which require their own installation procedure (if you didn't already know). 

I'm going to note these packages need to be installed by the user in the install documentation, but otherwise I'm going to close this issue.

**Comment by bretonics** [comment]
@definitelysean, yes I know they need to be installed from Bioconductor. A previous comment from Friday did not post stating this very thing: that it fails if you don't have these dependencies installed as it needs **biocLite**. Good call on adding that in the install instructions.

To further describe, I tested it with a fresh R install from CRAN and installation succeeds, which means that there might be an issue with a `brew r` install and maybe you you may need libgit2. Who knows without further testing.

Just to keep in mind in case someone comes along with this same issue.
