### ISSUE TITLE
Improved Model Performance Plot for celda_CG

### ISSUE THREAD

**Issue by definitelysean** [compbiomed/celda#93]
visualize_model_performance() should spit out a _grid_ of plots, where each plot is for one L, showing the various K performances.

@joshua-d-campbell let me know if this should be a priority or can be in the next milestone

**Comment by joshua-d-campbell** [comment]
Some issues and tweaks with this function when running on a real dataset:

1) Received warnings when tried to plot perplexity:

"1: Removed 15 rows containing non-finite values (stat_boxplot)."

2) Y-axis needs to be the same in each plot (i.e. the y-axis for each plot needs to encompass the full range of values across all models). This is so that one can easily compare across plots.

3) Add y-axis grid lines

4) Add bigger jitter for points

**Comment by definitelysean** [comment]
Hi @87875172 , can you take a look at Josh's comments above? Let me know if you need any help with the above points.

**Comment by joshua-d-campbell** [comment]
FYI, I'm guessing the problem for 1 is that when you have a small number of chains, ggplot isn't able to draw the boxplots and throws an error. Instead of boxplots, why don't we do a dot plot and then just draw a horizontal line for the median

**Comment by 87875172** [comment]
I'll fix problem 2 and 4. For problem 3, I am seeing both grid lines for y and x axes for simulated dataset on my end. @joshua-d-campbell can you maybe email me the plot you are seeing? 

For problem 1, I tested the function with simulated dataset with nchain = 1 and it worked without throwing error. I'll run it with a real dataset and see how it works. If boxplot is not good I'll switch to the dot plot and median line.

**Comment by definitelysean** [comment]
@joshua-d-campbell can you circulate the script you used to get problem 1?

Zhe's right about problem 4; the theme we're using (ggplot2::theme_bw() ) includes both X and Y axis gridlines, though we can make them thicker or change the color if need be.

**Comment by joshua-d-campbell** [comment]
For problem 4, it didn't draw the y-axis grid lines weren't being drawn only the the error from problem 1 occurred. So I don't think it is a problem after all.

**Comment by 87875172** [comment]
I ran the function on the dataset in the email and it shows Inf on the y-axis for all K and L. I think the problem is in the calculation of perplexity. I got 
1 'mpfr' number of precision  512   bits 
[1] Inf
when I try to calculate the perplexity of one celda_CG.res. Using method="harmonic" has the same problem. Method = "loglik" works fine. Should I post a issue about the calculate_perplexity function?

**Comment by definitelysean** [comment]
You can post an issue, Zhe. I'll have to see why we're getting Inf and how
to cope with it to still render a reasonable plot

**Comment by 87875172** [comment]
For the jitter and size of points, I'm thinking that maybe we can keep this consistent across package by adding global variables called for example jitter.width and point.size, if the default values need to be changed. It would be kind of strange if the plots in the package show different jitters and point sizes.

**Comment by definitelysean** [comment]
@87875172 I think that's a good thought. However, I don't think we should implement this with global variables. I think we should do one of the following:

- Make parameters to visualize_model_performance (with defaults that we like) that controls jitter and point size
- Define a custom ggplot2 theme which is used in all of the plots

The second option would be the most elegant, but the first would be a lot easier. Do you think you could implement that and we can make a themeing issue for when we have some more time?
